/* cubic_surface_nosplit.m

   Realize a smooth cubic surface over Q with a prescribed Galois action on its 27
   lines WITHOUT ever constructing the splitting field of the defining polynomial.

   This is the resolvent ("no-L") form of Algorithm 5.1 of Elsenhans--Jahnel.  The
   companion file cubic_surface_resolvent_twist.m solves the Galois descent over a
   concrete degree-|Gal(f)| number field L; that is impractical once |Gal(f)| is
   large (A5 -> degree 60, S5 -> degree 120, ...).  Here we instead:

     1. pick a prime p that splits f completely, so all roots lie in Z_p and the
        Galois group acts on them by honest permutations (the decomposition group is
        trivial -- this is what makes a single p-adic place suffice);
     2. form the 27-line resolvent algebra  A_27 = prod_j L^{H_j}  directly from the
        labelled p-adic roots: each factor is the field generated by an H_j-invariant
        of the roots, of degree = the size of a Gal-orbit on the 27 lines (<= 27,
        never |Gal(f)|);
     3. reduce each resolvent generator with PARI/GP's polredbest (the conditioning
        step -- without it the source lattice and hence the Clebsch invariants are
        astronomically large);
     4. descend the universal W(E6)-equivariant idempotent e (image = the six-
        dimensional Pinkham source V) to a rational map e_rho on A_27, and LLL-reduce
        a Q-basis of its image -- the analogue of D_rho but with no field L;
     5. evaluate the W(E6)-invariant Clebsch quantities through the normalized Coble
        gamma coordinates p-adically and rational-reconstruct them, then reconstruct
        a cubic via the pentahedral/trace construction (penta_pol_2_gl).

   The output surfaces are correct and their 27-line Galois action can be certified
   (LinesFrobeniusCycleTypesModQ below), but they are large: the intrinsic Clebsch /
   Delta_Cl height of these classes is the remaining barrier, unaffected by this
   method.  What this buys is reachability -- the large-|Gal(f)| classes that the
   field-based descent cannot start at all.

   Requirements:
     * load "cubic_surface_resolvent_twist.m";  first (for BuildUniversalCobleData,
       PinkhamGeneratorMatrices, LLLReduceRationalRowBasis, penta_pol_2_gl,
       ClebschInvariantsToPentahedralPolynomial, IsSmoothCubicSurface);
     * PARI/GP `gp` on the PATH (for polredbest).

   Main entry points:
       U  := BuildUniversalCobleData();
       RD := BuildResolvent27Data(U);                       // universal: q27 + idempotent
       r  := CubicSurfaceNoSplittingField(Gwe6, f : Universal := U, Resolvent27 := RD);
       cts := LinesFrobeniusCycleTypesModQ(r`surface);      // certify the 27-line group
*/

Q := RationalField();

Resolvent27RF := recformat< q27, idem, lineperms, phi27, bridge >;
NoSplitResultRF := recformat<
    surface, surface_unreduced, invariants, source_u, prime,
    orbit_sizes, galois_group, subgroup, universal >;

/* ------------------------------------------------------------------------- */
/* Universal 27-line data: q27 : Q^27 ->> V matched to Pinkham's six-dim rep, */
/* the rank-6 idempotent e with image V, and the 27-line permutation action.  */
/* ------------------------------------------------------------------------- */

BuildResolvent27Data := function(U : Print := true)
    mu6 := PinkhamGeneratorMatrices();         // [Mcr, Mcyc, Msw], 6x6, left on columns

    /* Picard lattice Pic = <H,E1,...,E6> = Q^7, with H = e_1, E_i = e_{i+1}. */
    V7   := VectorSpace(Q, 7);
    ee   := [ V7.i : i in [1..7] ];
    Hc   := ee[1];
    Ev   := [ ee[i+1] : i in [1..6] ];
    Gram := DiagonalMatrix(Q, [1,-1,-1,-1,-1,-1,-1]);
    ip   := func< u,v | (Matrix(1,7,Eltseq(u))*Gram*Transpose(Matrix(1,7,Eltseq(v))))[1,1] >;
    Kc   := -3*Hc + &+Ev;

    lines := [];
    for i in [1..6] do Append(~lines, Ev[i]); end for;
    for i in [1..6] do for j in [i+1..6] do Append(~lines, Hc-Ev[i]-Ev[j]); end for; end for;
    for i in [1..6] do Append(~lines, 2*Hc - &+[Ev[k] : k in [1..6] | k ne i]); end for;
    error if not (#lines eq 27 and &and[ip(L,Kc) eq -1 and ip(L,L) eq -1 : L in lines]),
        "27-line construction failed";

    /* W(E6) generators on Pic (row convention: row i = image of e_i, v |-> v*Mg),
       chosen to correspond to PinkhamGeneratorMatrices = [Cremona, 6-cycle, swap]. */
    mkM := func< imgs | Matrix(Q, [ Eltseq(imgs[i]) : i in [1..7] ]) >;
    Msw := mkM([ee[1],ee[3],ee[2],ee[4],ee[5],ee[6],ee[7]]);                 // swap E1,E2
    Mcr := mkM([2*ee[1]-ee[2]-ee[3]-ee[4], ee[1]-ee[3]-ee[4], ee[1]-ee[2]-ee[4],
                ee[1]-ee[2]-ee[3], ee[5],ee[6],ee[7]]);                       // Cremona at {1,2,3}

    S27 := SymmetricGroup(27);
    permOf := function(Mg)
        img := [ Index(lines, lines[a]*Mg) : a in [1..27] ];
        error if 0 in img, "a W(E6) generator did not permute the 27 lines";
        return S27 ! img;
    end function;

    BM := Matrix(Q, [ Eltseq(b) : b in Basis(Kernel(Gram*Transpose(Matrix(1,7,Eltseq(Kc))))) ]);
    coordOf := func< v | Solution(BM, v) >;    // coordinates of v in K-perp basis BM

    buildAll := function(Mcy)                  // Mcy: candidate 6-cycle generator
        gensPic := [Mcr, Mcy, Msw];
        P   := [ permOf(Mg) : Mg in gensPic ];
        psi := [ Matrix(Q,[ Eltseq(coordOf(BM[k]*Mg)) : k in [1..6] ]) : Mg in gensPic ];
        Psi := [ Transpose(pp) : pp in psi ];  // K-perp rep, left on column coordinates
        rows := [];                            // intertwiner system  C*Psi_i = mu6_i*C
        for i in [1..3] do
            Pm := Psi[i]; Mm := mu6[i];
            for x in [1..6] do for y in [1..6] do
                rw := [ Q!0 : t in [1..36] ];
                for k in [1..6] do rw[(x-1)*6+k] +:= Pm[k,y]; rw[(k-1)*6+y] -:= Mm[x,k]; end for;
                Append(~rows, rw);
            end for; end for;
        end for;
        return sub<S27|P>, P, Psi, Kernel(Transpose(Matrix(Q, rows)));
    end function;

    /* the 6-cycle direction is fixed by matching Pinkham's Mcyc; pick the variant
       generating W(E6) with a 1-dimensional intertwiner. */
    cands := [ mkM([ee[1],ee[7],ee[2],ee[3],ee[4],ee[5],ee[6]]),
               mkM([ee[1],ee[3],ee[4],ee[5],ee[6],ee[7],ee[2]]) ];
    chosen := 0;
    for ci in [1..#cands] do
        GP, P, Psi, K0 := buildAll(cands[ci]);
        if #GP eq 51840 and Dimension(K0) eq 1 then chosen := ci; break; end if;
    end for;
    error if chosen eq 0, "could not match the Pinkham six-cycle generator";
    GP, P, Psi, K0 := buildAll(cands[chosen]);

    v := Basis(K0)[1];
    C := ZeroMatrix(Q, 6, 6);
    for x in [1..6] do for k in [1..6] do C[x,k] := v[(x-1)*6+k]; end for; end for;
    error if not &and[ C*Psi[i] eq mu6[i]*C : i in [1..3] ], "intertwiner check failed";

    q27Pic := HorizontalJoin([ Matrix(Q,6,1,Eltseq(coordOf(lines[a]+Kc/3))) : a in [1..27] ]);
    q27    := C*q27Pic;                        // 6 x 27, e_ell |-> ell + K/3 in the Pinkham basis
    pmat   := func< g | Matrix(Q,27,27, [ <a^g, a, 1> : a in [1..27]]) >;
    error if not &and[ mu6[i]*q27 eq q27*pmat(P[i]) : i in [1..3] ], "q27 equivariance failed";

    /* G-equivariant idempotent with image V, via the orthogonal section (the 27-line
       permutation representation is orthogonal); no averaging over W(E6) is needed. */
    idem := Transpose(q27)*(q27*Transpose(q27))^-1*q27;
    error if not (idem*idem eq idem and Rank(idem) eq 6
                  and &and[ idem*pmat(P[i]) eq pmat(P[i])*idem : i in [1..3] ]),
        "idempotent check failed";

    /* phi27 : we6 -> S27, the geometric 27-line action (the inverse pairing makes it
       a homomorphism: Magma multiplies permutations left-to-right, matrices right-to-
       left, so phi6(w) q27 = q27 * Transpose(pmat(phi27(w))) for all w). */
    phi27 := hom< U`we6 -> S27 | [ pp^-1 : pp in P ] >;
    if Print then printf "Resolvent27 data: q27 (rank 6), idempotent e (rank 6), phi27 built.\n"; end if;

    return rec< Resolvent27RF | q27 := q27, idem := idem, lineperms := P,
                                phi27 := phi27, bridge := C >;
end function;

/* ------------------------------------------------------------------------- */
/* Normalized Coble gamma coordinates and the Clebsch invariants A..E.        */
/* gamma-hat is a polynomial map of the six cusp parameters t, exactly        */
/* equivariant for the signed-permutation W(E6) action; only even power sums  */
/* enter the Clebsch formulas, so the sign convention is immaterial.          */
/* ------------------------------------------------------------------------- */

NormalizedCobleGamma := function(t)
    seq3  := func< S | Sort(SetToSequence(S)) >;
    Delt  := func< I | &*[ Universe(t)| (t[I[b]]-t[I[a]]) : a,b in [1..#I] | a lt b ] >;
    sm    := func< I | &+[ t[i] : i in I ] >;
    res := []; s6 := &+t;
    for Iset in Subsets({1..6},3) do                 // 10 type-I coordinates
        if 1 notin Iset then continue; end if;
        I := seq3(Iset); Ic := seq3({1..6} diff Iset);
        Append(~res, Delt(I)*Delt(Ic)*sm(I)*sm(Ic)*s6);
    end for;
    pp := [];
    for b in {2..6} do rest := [x : x in [2..6] | x ne b];
        for ci in [2..4] do
            Append(~pp, [[1,b], Sort([rest[1],rest[ci]]),
                         Sort([x:x in rest|x ne rest[1] and x ne rest[ci]])]);
        end for;
    end for;
    for q in pp do for ord in [[q[1],q[2],q[3]],[q[1],q[3],q[2]]] do   // 30 type-II coordinates
        A:=ord[1]; B:=ord[2]; C:=ord[3];
        Append(~res, (t[A[2]]-t[A[1]])*(t[B[2]]-t[B[1]])*(t[C[2]]-t[C[1]])
            * &*[t[a]+sm(B):a in A] * &*[t[bb]+sm(C):bb in B] * &*[t[c]+sm(A):c in C]);
    end for; end for;
    return res;
end function;

ClebschFromGamma := function(g)
    PW := [ &+[ g[a]^e : a in [1..#g] ] : e in [2,4,6,8,10] ];
    P2:=PW[1]; P4:=PW[2]; P6:=PW[3]; P8:=PW[4]; P10:=PW[5];
    return [ -6*P2,
             -24*P4 + 41/16*P2^2,
             576/13*P6 - 396/13*P4*P2 + 29/13*P2^3,
             -62208/1171*P8 + 54864/1171*P6*P2 + 203616/1171*P4^2 - 61287/1171*P4*P2^2 + 13393/4684*P2^4,
             41472/155*P10 - 4605984/36301*P8*P2 - 106272/403*P6*P4 + 19990440/471913*P6*P2^2
               + 47719206/471913*P4^2*P2 - 7468023/471913*P4*P2^3 + 10108327/18876520*P2^5 ];
end function;

/* ------------------------------------------------------------------------- */
/* polredbest each resolvent via PARI/GP.  Returns, per input polynomial T,   */
/* a pair <P, beta> with P = reduced poly and beta the new generator written  */
/* in the old one (theta_new = beta(theta_old)), so a labelled root x of T    */
/* maps to the labelled root beta(x) of P.                                    */
/* ------------------------------------------------------------------------- */

PolredbestResolvents := function(polys, tmpdir)
    /* PARI's default 8 MB stack is fixed (parisizemax=0); polredbest on the
       degree-8/9 resolvents overflows it and prints nothing.  Start at 512 MB
       and let the stack grow to 4 GB, and wrap each polredbest in iferr so a
       hard failure falls back to the un-reduced polynomial (identity map) rather
       than aborting the whole batch of factors. */
    gpin := "default(parisize,\"512M\"); default(parisizemax,\"4G\");\n";
    for T in polys do
        cs := Coefficients(T);          // constant-first; Polrev([c0,c1,..]) = sum c_i x^i
        cstr := &cat[ Sprint(cs[i]) cat (i lt #cs select "," else "") : i in [1..#cs] ];
        gpin cat:= "pol=Polrev([" cat cstr cat "]); "
                 cat "v=iferr(polredbest(pol,1),ERR,[pol,Mod(x,pol)]); "
                 cat "print(Vec(v[1])); print(Vec(lift(modreverse(v[2]))));\n";
    end for;
    PrintFile(tmpdir cat "/nosplit_pr.gp", gpin cat "quit\n" : Overwrite);
    rc := System("cd " cat tmpdir cat " && gp -q nosplit_pr.gp > nosplit_pr.out 2>/dev/null");
    error if rc ne 0, "PARI/GP call failed -- is `gp` on the PATH?";
    Px := Universe(polys);
    /* keep only the coefficient-vector lines ("[...]"); PARI's stderr (stack-size
       warnings on the heavier resolvents) is discarded above. */
    out := [ l : l in Split(Read(tmpdir cat "/nosplit_pr.out"), "\n") | #l gt 0 and l[1] eq "[" ];
    error if #out ne 2*#polys, "unexpected gp output (got " cat IntegerToString(#out) cat " lines)";
    return [ < Px ! Reverse(eval out[2*i-1]), Px ! Reverse(eval out[2*i]) > : i in [1..#polys] ];
end function;

/* ------------------------------------------------------------------------- */
/* Main no-L pipeline.                                                         */
/* ------------------------------------------------------------------------- */

CubicSurfaceNoSplittingField := function(Gwe6, f : Universal := false,
                                                   Resolvent27 := false,
                                                   Iso := false,
                                                   Prec := 900,
                                                   HeightBound := 1,
                                                   SampleCap := 1500,
                                                   MaxMonDegree := 6,
                                                   MaxSurfaces := 10,
                                                   SplitPrimeBound := 200000,
                                                   MaxPrimTries := 60,
                                                   TmpDir := ".",
                                                   Print := true)
    U  := Universal;    if Type(U)  eq BoolElt then U  := BuildUniversalCobleData(: Print := Print); end if;
    RD := Resolvent27;  if Type(RD) eq BoolElt then RD := BuildResolvent27Data(U : Print := Print); end if;
    we6 := U`we6; q27 := RD`q27; idem := RD`idem; phi27 := RD`phi27;
    S27 := SymmetricGroup(27);

    Pq := PolynomialRing(Q);
    fz := Pq ! f; d := Degree(fz);
    error if not (IsMonic(fz) and IsIrreducible(fz) and &and[Denominator(c) eq 1 : c in Coefficients(fz)]),
        "f must be monic, irreducible, with integer coefficients";

    /* a totally-split prime: f = d distinct linear factors mod p */
    splitp := 0;
    for q in PrimesInInterval(d+2, SplitPrimeBound) do
        fq := Factorization(ChangeRing(fz, GF(q)));
        if #fq eq d and &and[ Degree(t[1]) eq 1 : t in fq ] then splitp := q; break; end if;
    end for;
    error if splitp eq 0, "no totally-split prime found below SplitPrimeBound";

    P, _, S := GaloisGroup(fz : Prime := splitp);
    error if InertiaDegree(S`Ring) ne 1, "GaloisGroup did not use the split prime";
    error if Order(P) ne Order(Gwe6), Sprintf("|Gal(f)| = %o but |Gwe6| = %o", Order(P), Order(Gwe6));
    if Type(Iso) eq BoolElt then
        ok, psi := IsIsomorphic(P, Gwe6); error if not ok, "Gal(f) is not isomorphic to Gwe6";
    else psi := Iso; end if;

    act    := func< g | phi27(psi(g)) >;
    Pelts  := [ g : g in P ];
    orbs   := [ Sort(SetToSequence(o)) : o in Orbits(sub<S27 | [act(P.i) : i in [1..Ngens(P)]]>) ];
    if Print then printf "split prime %o, Gal(f) order %o, 27-line orbit sizes %o\n",
        splitp, Order(P), [#o : o in orbs]; end if;

    p := splitp;
    rts0 := [ GaloisRoot(i, S : Prec := Prec) : i in [1..d] ];
    Rp   := FieldOfFractions(Universe(rts0));   // p-adic FIELD: Vandermonde inverts even
    rts  := [ Rp ! x : x in rts0 ];             // when x_ell collide mod p (non-unit det)

    recon := function(z)                       // p-adic -> rational (split prime: Rp = Z_p)
        comps := Eltseq(z);
        if #comps gt 1 and exists{c : c in comps[2..#comps] | Valuation(c) lt Prec div 2} then return false,0; end if;
        zb := comps[1]; vv := Valuation(zb); u := vv ge 0 select zb else zb*p^(-vv);
        ok, r := RationalReconstruction(Integers(p^(AbsolutePrecision(u)))!(Integers()!u));
        if not ok then return false,0; end if;
        return true, vv ge 0 select r else r/p^(-vv);
    end function;

    /* per-orbit resolvent generator x_ell: theta_{l0} = sum_{h in Stab} h(theta_0),
       theta_0 a generic combination of monomials in the roots; x_ell = (coset
       rep)(theta).  Require x_ell distinct within each orbit.  A transitive
       stabiliser can kill all low-degree power sums (e.g. orbit structure
       [1,2,8,16] needs mixed degree-4 products), so escalate the monomial degree
       until separation is achieved.  The stabiliser/coset data below depends only
       on the group action, not on the roots or coefficients. */
    stabOf := []; cosetRep := [];
    for oi in [1..#orbs] do o := orbs[oi]; l0 := o[1];
        Hs := [ g : g in Pelts | l0^(act(g)) eq l0 ];
        gell := AssociativeArray();
        for g in Pelts do ell := l0^(act(g)); if not IsDefined(gell,ell) then gell[ell]:=g; end if; end for;
        Append(~stabOf, Hs); Append(~cosetRep, gell);
    end for;
    MonsUpTo := function(D)                          // all non-decreasing index tuples of length 1..D
        cur := [ [i] : i in [1..d] ]; ms := cur;
        for len in [2..D] do
            nxt := [];
            for m in cur do for i in [m[#m]..d] do Append(~nxt, m cat [i]); end for; end for;
            cur := nxt; ms cat:= cur;
        end for;
        return ms;
    end function;
    /* Trace monomial vectors: T[ell][t] = sum_{h in Stab(l0)} prod_{v in mons[t]} R[v^(h g_ell)].
       These do not depend on the coefficients co, and
           x_ell = sum_{h in Stab} sum_t co[t] mon_t(h g_ell) = sum_t co[t] T[ell][t],
       so once T is built the whole random-co search is just cheap linear combinations.
       Precomputing T (instead of re-tracing every trial) is what makes the large-group,
       high-degree cases (d=10, |G|=240 -- ~10^3 stabiliser-trace terms per line) tractable. */
    orbIdx := [ 0 : i in [1..27] ];
    for oi in [1..#orbs] do for ell in orbs[oi] do orbIdx[ell] := oi; end for; end for;
    TraceMonVecs := function(R, mons)
        Ru := Universe(R);
        T := [ [ Ru!0 : t in [1..#mons] ] : ell in [1..27] ];
        for oi in [1..#orbs] do Hs := stabOf[oi]; gell := cosetRep[oi];
            for ell in orbs[oi] do
                acc := [ Ru!0 : t in [1..#mons] ];
                for h in Hs do g := h*gell[ell];
                    rr := [ R[i^g] : i in [1..#R] ];             // roots permuted by g, once
                    for t in [1..#mons] do acc[t] +:= &*[ rr[v] : v in mons[t] ]; end for;
                end for;
                T[ell] := acc;
            end for;
        end for;
        return T;
    end function;
    combine := func< co, T | [ &+[ co[t]*T[ell][t] : t in [1..#co] ] : ell in [1..27] ] >;
    isSep   := func< xp, thr | &and[ &and[ Valuation(xp[o[i]]-xp[o[jj]]) lt thr : i,jj in [1..#o]|i lt jj ]
                                     : o in orbs | #o gt 1 ] >;
    /* search a separating combination cheaply at low precision, escalating degree,
       then rebuild it at full precision */
    rtsLo := [ GaloisRoot(i, S : Prec := 80) : i in [1..d] ];
    RpLo  := FieldOfFractions(Universe(rtsLo)); rtsLo := [ RpLo ! x : x in rtsLo ];
    xpad := []; orbOf := orbIdx; usemons := []; usco := []; gotco := false; usedeg := 0;
    for D in [3..MaxMonDegree] do
        mons := MonsUpTo(D);
        Tlo  := TraceMonVecs(rtsLo, mons);
        for tries in [1..MaxPrimTries] do
            co := [ Random([1..6]) : t in [1..#mons] ];
            if isSep(combine(co, Tlo), 40) then usemons := mons; usco := co; usedeg := D; gotco := true; break; end if;
        end for;
        if gotco then break; end if;
    end for;
    error if not gotco, Sprintf("no separable primitive element (up to degree %o)", MaxMonDegree);
    if Print then printf "primitive element: degree-<=%o monomials\n", usedeg; end if;
    xpad := combine(usco, TraceMonVecs(rts, usemons));       // rebuild at full precision

    /* polredbest -> condition the resolvent fields (x_ell <- beta(x_ell)) */
    Px := PolynomialRing(Q);
    reconPoly := function(zs)
        cf := []; for c in Coefficients(&*[PolynomialRing(Rp).1 - z : z in zs]) do
            ok, r := recon(c); error if not ok, "resolvent reconstruction failed (raise Prec)"; Append(~cf, r);
        end for; return Px ! cf;
    end function;
    multi := [ oi : oi in [1..#orbs] | #orbs[oi] gt 1 ];
    red   := PolredbestResolvents([ reconPoly([xpad[ell] : ell in orbs[oi]]) : oi in multi ], TmpDir);
    for t in [1..#multi] do
        bjR := ChangeRing(red[t][2], Rp);
        for ell in orbs[multi[t]] do xpad[ell] := Evaluate(bjR, xpad[ell]); end for;
    end for;
    error if not &and[ &and[ Valuation(xpad[o[i]]-xpad[o[jj]]) lt Prec div 2 : i,jj in [1..#o]|i lt jj] : o in orbs|#o gt 1 ],
        "polredbest collapsed roots mod p -- re-run";
    if Print then printf "applied polredbest to %o resolvent field(s)\n", #multi; end if;

    /* descended idempotent e_rho on A_27 (power basis), via per-orbit Vandermonde */
    pb := []; for oi in [1..#orbs] do for k in [0..#orbs[oi]-1] do Append(~pb, <oi,k>); end for; end for;
    eRp := ChangeRing(idem, Rp);
    Vdinv := [* *];
    for o in orbs do s := #o; Vd := ZeroMatrix(Rp, s, s);
        for i in [1..s] do for kk in [0..s-1] do Vd[i,kk+1] := xpad[o[i]]^kk; end for; end for;
        Append(~Vdinv, Vd^-1);
    end for;
    M := ZeroMatrix(Q, 27, 27);
    for c in [1..27] do
        j := pb[c][1]; k := pb[c][2];
        w := [ &+[ eRp[ell,m]*xpad[m]^k : m in orbs[j] ] : ell in [1..27] ];
        for jp in [1..#orbs] do o := orbs[jp]; s := #o;
            cvec := Vdinv[jp] * Matrix(Rp, s, 1, [ w[o[i]] : i in [1..s] ]);
            for kk in [0..s-1] do
                ok, r := recon(cvec[kk+1,1]); error if not ok, "e_rho reconstruction failed (raise Prec)";
                M[Index(pb,<jp,kk>), c] := r;
            end for;
        end for;
    end for;
    error if not (M*M eq M and Rank(M) eq 6), "descended idempotent is not a rank-6 projection";

    B6 := LLLReduceRationalRowBasis(Matrix(Q, [ Eltseq(b) : b in Basis(Image(M)) ]));
    q27K := ChangeRing(q27, Rp);
    pbOfLine := [ [ ci : ci in [1..27] | pb[ci][1] eq orbOf[ell] ] : ell in [1..27] ];
    srcOf := function(ac)                       // power-basis coords -> six-dim source point t
        a := [ &+[ ac[ci]*xpad[ell]^(pb[ci][2]) : ci in pbOfLine[ell] ] : ell in [1..27] ];
        return [ &+[ q27K[i,m]*a[m] : m in [1..27] ] : i in [1..6] ];
    end function;
    clebschOf := function(ac)
        cl := ClebschFromGamma(NormalizedCobleGamma(srcOf(ac)));
        out := []; for z in cl do ok,r := recon(z); if not ok then return false, []; end if; Append(~out, r); end for;
        return true, out;
    end function;

    /* Search source points by increasing height h = 1..HeightBound, keeping the
       smallest smooth surface.  The shell {u : max|u_i| = h, gcd(u) = 1} grows
       like (2h+1)^6, so test at most SampleCap points per shell (a random
       subsample of the larger shells).  Sweeping low heights first favours
       smaller surfaces, and -- unlike a single top-shell scan -- never skips a
       height where a smooth surface is easy to find. */
    if Print then printf "enumerating source points (height <= %o, <= %o per shell)...\n",
        HeightBound, SampleCap; end if;
    cands := [];
    for h in [1..HeightBound] do
        pts := [];
        if (2*h+1)^6 le 8*SampleCap then                 // small shell: take it all
            allp := [];
            for u in CartesianPower([-h..h], 6) do
                uu := [u[i]:i in [1..6]];
                if Max([Abs(x):x in uu]) eq h and GCD(uu) eq 1 then Append(~allp, uu); end if;
            end for;
            if #allp le SampleCap then pts := allp;
            else pts := [ allp[Random(1,#allp)] : i in [1..SampleCap] ]; end if;
        else                                             // huge shell: random subsample
            seen := {}; att := 0;
            while #pts lt SampleCap and att lt 40*SampleCap do
                att +:= 1;
                uu := [ Random(-h,h) : i in [1..6] ];
                if Max([Abs(x):x in uu]) eq h and GCD(uu) eq 1 and uu notin seen then
                    Include(~seen, uu); Append(~pts, uu);
                end if;
            end while;
        end if;
        for uu in pts do
            ac := [ &+[ uu[r]*B6[r][ci] : r in [1..6] ] : ci in [1..27] ];
            ok, inv := clebschOf(ac);
            if ok and inv[5] ne 0 then
                pol5 := ClebschInvariantsToPentahedralPolynomial(inv);
                if Discriminant(pol5) ne 0 then
                    gl := penta_pol_2_gl(pol5);
                    if IsSmoothCubicSurface(gl) then
                        Append(~cands, <Max([Abs(c):c in Coefficients(gl)]), gl, inv, uu>);
                    end if;
                end if;
            end if;
            if #cands ge MaxSurfaces then break; end if;
        end for;
        if #cands ge MaxSurfaces then break; end if;
    end for;
    error if #cands eq 0, "no smooth surface found up to this height (raise HeightBound, or Prec)";
    Sort(~cands, func< a,b | a[1] - b[1] >);
    best := cands[1];
    if Print then printf "%o smooth surface(s); smallest has %o-digit coefficients\n",
        #cands, #Sprint(best[1]); end if;

    return rec< NoSplitResultRF |
        surface := best[2], surface_unreduced := best[2], invariants := best[3],
        source_u := best[4], prime := splitp, orbit_sizes := [#o : o in orbs],
        galois_group := P, subgroup := Gwe6, universal := U >;
end function;

/* ------------------------------------------------------------------------- */
/* Certification: Frobenius cycle types on the 27 lines of gl mod q.          */
/* The line lengths are the cycle lengths of Frobenius, so their l.c.m. is    */
/* the order of the corresponding Galois element.  Collecting these over      */
/* several q pins the 27-line Galois group (e.g. A5 has element orders only   */
/* {1,2,3,5}; an order-3 and an order-5 force 15 | |G|, hence G = A5 inside    */
/* its W(E6) class; for S5 additionally find an order-4 or order-6 element).   */
/* ------------------------------------------------------------------------- */

/* cycle type of Frobenius at q on the 27 lines of gl (= factor degrees of the
   degree-27 line resolvent mod q), or [] if q is bad or the random slice failed. */
FrobCycleTypeModQ := function(glZ, q, Tries)
    Fq  := GF(q);
    R4q := PolynomialRing(Fq, 4);
    glq := R4q ! glZ;
    P3  := ProjectiveSpace(Fq, 3); CR := CoordinateRing(P3);
    if not IsEmpty(Scheme(P3, [ Derivative(CR!glq, i) : i in [1..4] ])) then return []; end if;
    PT<T> := PolynomialRing(Fq);
    for attempt in [1..Tries] do
        repeat Mt := Matrix(Fq,4,4,[Random(Fq):i in [1..16]]); until Determinant(Mt) ne 0;
        g := Evaluate(glq, [ &+[Mt[i,j]*R4q.j : j in [1..4]] : i in [1..4] ]);
        A4 := PolynomialRing(Fq, 4); Pxy<XX,YY> := PolynomialRing(A4, 2);
        Fb := Evaluate(g, [XX, YY, A4.1*XX + A4.2*YY, A4.3*XX + A4.4*YY]);
        cfs := [ MonomialCoefficient(Fb, XX^k*YY^(3-k)) : k in [0..3] ];
        Sch := Scheme(AffineSpace(A4), cfs);
        if Dimension(Sch) eq 0 and Degree(Sch) eq 27 then
            A5 := PolynomialRing(Fq, 5);
            emb := hom< A4 -> A5 | [A5.1,A5.2,A5.3,A5.4] >;
            lam := A5.1 + Random([2..q-1])*A5.2 + Random([2..q-1])*A5.3 + Random([2..q-1])*A5.4;
            Jel := EliminationIdeal(ideal< A5 | [emb(F):F in cfs] cat [A5.5 - lam] >, 4);
            gg := [ b : b in Basis(Jel) | b ne 0 ];
            if #gg ge 1 then
                fa := Evaluate(gg[1], [0,0,0,0,T]);
                if Degree(fa) eq 27 and IsSquarefree(fa) then
                    return Sort([ Degree(tt[1]) : tt in Factorization(fa) ]);
                end if;
            end if;
        end if;
    end for;
    return [];
end function;

LinesFrobeniusCycleTypesModQ := function(gl : QStart := 11, QStop := 1500, MaxQ := 40,
                                              Tries := 25, Print := true)
    glZ := PolynomialRing(Q, 4) ! gl;
    results := [];
    for q in PrimesInInterval(QStart, QStop) do
        ct := FrobCycleTypeModQ(glZ, q, Tries);
        if #ct eq 0 then continue; end if;
        Append(~results, <q, ct>);
        if Print then printf "  q=%-5o : %o   (element order %o)\n", q, ct, LCM(ct); end if;
        if #results ge MaxQ then break; end if;
    end for;
    return results;
end function;

/* ------------------------------------------------------------------------- */
/* Fuller certification.  Compare the SET of mod-q Frobenius cycle types on    */
/* the 27 lines to the cycle types of the target group G (mapped into S27 by   */
/* phi27 = Resolvent27`phi27).  Containment (no "alien" type) rules out an      */
/* accidentally generic, too-large surface; seeing ALL of G's cycle types      */
/* rules out a too-small one -- a proper subgroup H < G realises only H's cycle */
/* types, a strict subset of G's, so it can never reach full coverage.  This is */
/* not a proof of the action (distinct groups can share a cycle-type set on the */
/* 27 lines), but it is far stronger than matching element orders alone.        */
/* Verdicts: CERTIFIED (contained + full coverage), CONSISTENT (contained but   */
/* some of G's cycle types not yet seen -- raise MaxQ/QStop), REJECTED (an      */
/* alien cycle type appeared, so the 27-line group is not inside G).            */
/* ------------------------------------------------------------------------- */
NoSplitCertRF := recformat< verdict, subset_ok, coverage, n_target, n_seen,
                            n_primes, extra_types, missing_types >;
LinesGaloisCertificate := function(gl, G, phi27 : QStart := 11, QStop := 40000,
                                   MinPrimes := 40, MaxPrimes := 220, Tries := 25, Print := true)
    cyc := func< p | Sort(&cat[ [ c[1] : j in [1..c[2]] ] : c in CycleStructure(p) ]) >;
    target := {}; for c in ConjugacyClasses(G) do Include(~target, cyc(phi27(c[3]))); end for;
    glZ := PolynomialRing(Q, 4) ! gl;
    seen := {}; alien := {}; np := 0;
    for q in PrimesInInterval(QStart, QStop) do
        ct := FrobCycleTypeModQ(glZ, q, Tries);
        if #ct eq 0 then continue; end if;
        np +:= 1;
        if ct notin target then Include(~alien, ct); break; end if;   // an alien type is decisive
        Include(~seen, ct);
        if (seen eq target and np ge MinPrimes) or np ge MaxPrimes then break; end if;
    end for;
    miss := target diff seen; subset_ok := #alien eq 0;
    verdict := (not subset_ok) select "REJECTED"
               else (#miss eq 0 select "CERTIFIED" else "CONSISTENT");
    if Print then
        printf "certificate: %o  (%o/%o of G's cycle types over %o primes%o)\n",
            verdict, #target - #miss, #target, np,
            subset_ok select "" else Sprintf(", ALIEN type %o", Random(alien));
    end if;
    return rec< NoSplitCertRF | verdict := verdict, subset_ok := subset_ok,
        coverage := (#target eq 0) select 1 else (#target - #miss) / #target,
        n_target := #target, n_seen := #target - #miss, n_primes := np,
        extra_types := alien, missing_types := miss >;
end function;

/*
Example session.

    load "cubic_surface_resolvent_twist.m";
    load "cubic_surface_nosplit.m";

    U  := BuildUniversalCobleData();
    RD := BuildResolvent27Data(U);
    cl := SubgroupClasses(U`we6);

    // A5 (a quintic with Galois group A5); pick a W(E6) class isomorphic to it
    Pq<t> := PolynomialRing(RationalField());
    f  := t^5 + 20*t + 16;
    A5 := [ c`subgroup : c in cl | Order(c`subgroup) eq 60 and IsIsomorphic(c`subgroup, GaloisGroup(f)) ][1];
    r  := CubicSurfaceNoSplittingField(A5, f : Universal := U, Resolvent27 := RD, TmpDir := "/tmp");
    cts := LinesFrobeniusCycleTypesModQ(r`surface);
    // orders present include 3 and 5  =>  G = A5 (no degree-60 field was built)

The surfaces are large (their intrinsic Clebsch height is the unavoidable cost of
these classes); what the method provides is that the large-|Gal(f)| classes are
reachable at all.  PARI/GP must be available for the polredbest conditioning step.
*/
